# cf http://qiita.com/pine613/items/3fdc4e1bd06065cc056d
build: off
shallow_clone: true
skip_tags: true
skip_branch_with_pr: true
branches:
  except:
    - poc
init:
  - git config --global core.autocrlf input
install:
  - choco install strawberryperl
  - SET "PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%"
  - curl -fsSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
test_script:
  - prove -lr t xt
