name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  ubuntu:
    name: ubuntu perl ${{ matrix.perl-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.8-buster'
          - '5.10-buster'
          - '5.16-buster'
          - '5.18-buster'
          - 'latest'
          - 'threaded'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v5
      - name: change /etc/apt/sources.list
        run: perl -i -pe 's/(deb|security).debian.org/archive.debian.org/' /etc/apt/sources.list
        if: endsWith(matrix.perl-version, '-buster')
      - name: Install deb packages
        run: apt-get -qq update && apt-get -qq install -y unzip libdb-dev
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install -g --with-develop --with-recommends --show-build-log-on-failure
        if: matrix.perl-version != '5.8-buster'
      - name: Install Dependencies
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install -g --with-develop --with-recommends --show-build-log-on-failure --resolver Fixed,CPAN::Meta::Requirements@2.140
        if: matrix.perl-version == '5.8-buster'
      - name: Run Tests
        run: prove -lr --timer t xt

  macos:
    name: macos ${{ matrix.perl }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - perl: /usr/bin/perl
            prove: /usr/bin/prove
            sudo: 'sudo -H'
          - perl: /opt/homebrew/bin/perl
            prove: /opt/homebrew/bin/prove
            sudo: ''
    steps:
      - uses: actions/checkout@v5
      - name: perl -V
        run: ${{ matrix.perl }} -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | ${{ matrix.sudo }} ${{ matrix.perl }} - install -g --with-develop --with-recommends --show-build-log-on-failure
      - name: Run Tests
        run: ${{ matrix.prove }} -lr --timer t xt

  windows:
    name: windows perl ${{ matrix.tester-id }}
    runs-on: windows-latest
    strategy:
      matrix:
        tester-id:
          - '0'
          - '1'
          - '2'
    steps:
      - uses: actions/checkout@v5
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install -g --with-develop --with-recommends --show-build-log-on-failure
      - name: Run Tests
        run: perl author\split-run "t\*.t xt\*.t xt\*\*.t" ${{ matrix.tester-id }}/3 prove -l --timer
